site_name: Kuzaku — Документация

repo_url: https://github.com/kuzaku-developers/kuzaku-docs
repo_name: kuzaku-developers/kuzaku-docs
copyright: Copyright &copy; 2021 - 2021 BANana
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: slate
    accent: red
    primary: red
    
  language: 'ru'
  favicon: assets/kuzaku.png
  logo: assets/kuzaku.png
  features:
    - search.suggest
    - search.highlight
    - navigation.expand
plugins:
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      custom_templates: templates
  - search:
      lang: ru
extra:
  homepage: https://kuzaku.ml
  social:
    - icon: material/web
      link: https://kuzaku.ml
    - icon: fontawesome/brands/github
      link: https://github.com/kuzaku-developers/kuzaku
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VxetPBhgC7
nav:
  - 'Добро пожаловать!': 'index.md'
  - 'Начало':
    - 'Публичное API': 'get-started/public-api.md'
    - 'Kuzaku premium': 'additional-info/kuzaku-premium.md'
  - 'Доп. информация':
    - 'Как пригласить Kuzaku': 'additional-info\kuzaku-invitation.md'
  - 'Полезные ссылки':
    - 'Контакты разработчиков': 'good-links/contacts.md'
    - 'Оффициальный вебсайт 🌐': 'https://kuzaku.ml'
    - 'Пригласить Kuzaku 🌐': 'https://discord.com/oauth2/authorize?client_id=778648045960298568&scope=bot+applications.commands&permissions=473197655'
    
  - 'Другое':
    - 'Часто задаваемые вопросы': 'another/faq.md'
    - 'Список изменений': 'another/changelog.md'
  - 'Настройка бота':
      - 'Музыка': 'setting-up-bot/music-commands.md'
